### ISSUE TITLE
Enochian Timer does not update

### ISSUE THREAD

**Issue by Griever92** [anoyetta/ACT.MPTimer#18]
The Enochian Timer does not appear to function with my game.

Enochian Status UP (27s remain) | Enochian Timer still shows "Over"
![enochian timer](https://cloud.githubusercontent.com/assets/7936026/8421426/b88bae04-1e8b-11e5-9e61-9af3db80f42e.PNG)

Settings for Enochian Timer are below
![enochian timer2](https://cloud.githubusercontent.com/assets/7936026/8421435/de0dc61c-1e8b-11e5-8366-c84f3b6e1d01.PNG)

**Comment by anoyetta** [comment]
Sorry.
It doesn't correspond to English log at present.
It's corrected by the next version.

**Comment by anoyetta** [comment]
Please try this version.
https://github.com/anoyetta/ACT.MPTimer/releases/tag/v1.5.11

**Comment by Griever92** [comment]
I can confirm that the new version resolves the issue with the English log.

Thanks!
