### ISSUE TITLE
Enochian Timer for french client

### ISSUE THREAD

**Issue by Gadwin** [anoyetta/ACT.MPTimer#22]
Hello :)

Is it possible to make your plugin work for the french client ?

When you use Enochian, the sentence is : Vous utilisez Énochien.
When got Enochian buff, the sentence is : Vous bénéficiez de l'effet Énochien.
When you lost Enochian buff, the sentence is : Vous perdez l'effet Énochien.

Thank you ^^

**Comment by anoyetta** [comment]
The following sentences are needed.

You use Enochian.
You lose the effect of Enochian.
You gain the effect of Umbral Ice.
You gain the effect of Umbral Ice II.
You gain the effect of Umbral Ice III.
You lose the effect of Umbral Ice.
You lose the effect of Umbral Ice II.
You lose the effect of Umbral Ice III.
You cast Blizzard IV.

**Comment by Gadwin** [comment]
Thank you for the answer !!!

You use Enochian. =============================> Vous utilisez Énochien.
You gain the effet of Enochian. ====================> Vous bénéficiez de l'effet Énochien.
You lose the effect of Enochian. ===================> Vous perdez l'effet Énochien.
You gain the effect of Umbral Ice. ==================> Vous bénéficiez de l'effet Glace ombrale.
You gain the effect of Umbral Ice II. =================> Vous bénéficiez de l'effet Glace ombrale II.
You gain the effect of Umbral Ice III. =================> Vous bénéficiez de l'effet Glace ombrale III.
You lose the effect of Umbral Ice. ===================> Vous perdez l'effet Glace ombrale.
You lose the effect of Umbral Ice II. ==================> Vous perdez l'effet Glace ombrale II.
You lose the effect of Umbral Ice III. ==================> Vous perdez l'effet Glace ombrale III.
You cast Blizzard IV. ==============================> Vous lancez Giga Glace.

**Comment by anoyetta** [comment]
I dealt with a French client.
Try this.
https://github.com/anoyetta/ACT.MPTimer/releases/tag/v1.5.13

**Comment by Gadwin** [comment]
Perfect !

Thank you very much :)
