### ISSUE TITLE
enochian timer stays at "over"

### ISSUE THREAD

**Issue by gonzeau** [anoyetta/ACT.MPTimer#24]
Hello, I am having problem getting enochian timer to work, I am using english client, the most recent version of MP Timer but it's always staying on over. This is the setting i am using.
![enochian](https://cloud.githubusercontent.com/assets/13663761/9091834/66861804-3b70-11e5-91b2-8384ff3cab69.jpg)

**Comment by gonzeau** [comment]
I was just able to get it to work. Keep up the good work :)

**Comment by Bloodshot911** [comment]
Hey, would you mind describing how you manage to make it work ? I got the exact same problem.

Thanks !
